name: Share English Teaching App Assistant
description: Custom agent for the Node.js/Express English vocabulary teaching application
version: 1.0.0

capabilities:
  - svg_asset_automation
  - vocabulary_management
  - activity_template_guidance
  - localization_support
  - deck_routing_validation
  
triggers:
  svg_added:
    description: Automatically process new SVG files
    actions:
      - run: node build_object_ejs.js
        when: SVG added to public/image/svg/objects/
      - run: node build_supply_ejs.js
        when: SVG added to public/image/svg/supplies/
      - run: node process_svgs.js
        when: General SVG processing needed
      
  vocabulary_updated:
    description: Validate vocabulary changes
    actions:
      - check: Corresponding images exist in public/image/
      - check: Corresponding audio exists in public/audio/
      - check: Metadata completeness (id, book, theme, meaning, image, audio)
      
  activity_created:
    description: Guide new activity creation
    actions:
      - suggest: Template location in views/activities/
      - enforce: Proper wrapper convention (<div class="object"> or <div class="supply">)
      - update: Routing in routes/main.js
      
  localization_changed:
    description: Ensure translation completeness
    actions:
      - scan: Untranslated keys in code and templates
      - prompt: Updates to locales/en.json and locales/ja.json
      - verify: i18n usage (req.__(...))

conventions:
  svg_filenames:
    - Use underscores for spaces
    - Use parentheses for disambiguation
    - Reference: public/image/svg/README.md
    
  activity_routing:
    - Activities rendered via /activities/:activity and /activities/:activity/:id
    - Deck data from DB (links table) or vocabulary.js
    
  ejs_wrappers:
    - Objects: <div class="object" data-shape="...">
    - Supplies: <div class="supply" data-shape="...">
    
  error_handling:
    - 404 errors render views/404.ejs
    - General errors render views/error.ejs

tech_stack:
  runtime: Node.js
  framework: Express
  templating: EJS
  database: MySQL
  realtime: Socket.IO
  localization: i18n
  frontend: Vanilla JavaScript, SVG

key_files:
  server: share.js
  routes: routes/main.js, routes/teachers.js, routes/media.js, routes/labs.js, routes/letters.js, routes/things.js, routes/io.js
  vocabulary: public/vocabulary.js
  svg_processors: build_object_ejs.js, build_supply_ejs.js, process_svgs.js
  localization: locales/en.json, locales/ja.json
  
workflows:
  development:
    start: nodemon share.js
    build_svgs: node build_object_ejs.js && node build_supply_ejs.js
    test: npm test
    
  database:
    connection: MySQL pool in routes/main.js
    credentials: .env file (PORT, DB_HOST, DB_USER, DB_PASSWORD, DB_NAME)
    key_tables: links (activity decks)
